language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-24
jdk:
- oraclejdk8
before_script:
- rm -rf ~/.gradle/caches/
script:
- ./gradlew ":abtesting:build"
after_success:
- ".buildscript/deploy_snapshot.sh"
env:
  global:
  - secure: WrXG24a4jqjG4FISR8IMBz3dmuNQubxn2jlyAByXmHBcNqbKnLfV5s1oSHiS5nUO/H1E/B14U9s73JZlp23s9HL0kG7vW9Br0aah9zoc5QSksSkZA4moA4cD/nObFnS3qJBoES/PkeehpaE5ATGjLsdZp+TimNG1VeFeaCUGefefgrxcgNa9VvnvkMpuuy7QCw/h89TZ7WHYc4ieq+v6xycSfIgb5HmqVuhXkBIAhP42/Rt9uSsV1no7NeCsYFaRy9PAZnV0tnzguxOimhqDLe0Z3EsKJ9OdhZILqmUODSR/kJBw9fhxeURspbiH60/sJSZwO+rYkbRBP+Dd3NTm6Af0axwi512LZaOH00phMbsDF7Lg/rWtV6URQj3xm/FALe0VP1jQZn6pNI5gXsY1oLXEZVQVUIpP4Z83jI/qXRSCtf/3azhGfEGz3wjqMCD4UA5cohf/L7GH9n9Crka0ePWnTEdgAvVFNUSny3qFGG+7S3vTM4PMu45GfJaps8MFSC68oNreylT4wKPdq3pL0p9mCYU42tRaJERx6IkWx8qJLQ603+1ShYHtgadTtO2jOrJSuFNMcXuiPyO/DwrXquU7VwO7TzjegymdMzwxWSy8NhWIf9genlQqxGPwlA/tu6co3u3f4sEqTkMLog5VbTayiWHLMtjRVBT8RKm5p6Y=
  - secure: AIAlCH3SxSN0mBmPNs7y1XYcJnzgUoA6hMut+JVLUpehHI1hNJM3GNCQ/mcejtaqOzxSLLGFP6o2obz0xibeHcmQPLolFupSWU38GGJ/WgfMovI2LQ0wXwgvUZZsmslUbV7tWQ7k5Q524hMZhXF/DcjQ3PvJHLnhwnmV5m230quAv7VKJSLJgkfNC35YGxTFPbVTgfE8le3ixEvPYFRxa2cAh2UfAYm3HHiTQOmK+YChjzMPNzGqHJcXB4UEwNcg66t+gOkayiFWvZj0lAJi2vu/jBztpbxFAvb/fCgqhv83Yk+jzyJgmBYL+aVgqXPC6korAuaSTP0vF2LPxQXbMb9HWwN5KbwtEtGk7CbFpM3UL+9BtmwM5tvduVzy32EoU9Z8odjZyNJOef18xrubeqAQI1lPwGXBi3CdSvwc/oULZSv4krAeliIRVfT5lQdBpCMALqFIE2OjnFFfl3qZKb1FHD7oVLpZAVgR8wrDWOxssL4mSmCpV858EhOAzafIwLfjM9tZgJICHZxNQxgL9zEqkHDUeHdhTs8gVx1hnLm9PY4D88ye6yti0KM8cWnwDIl9BZqRPC3TyWzLkwIknXI6R9twK5IPsAwg+/cj2H3oOaOarDvy8xMSAnlFfwWhpjpcpgT/yzoPE/rgPvCfdju5TzizBPHgAMIeWYCYYV4=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
